### PR TITLE
*: fix data race that may cause panic and concurrency request limit bug

### LINKED ISSUE #1222: client_batch have race when enable-forwarding is true
following is the data race. and the race will cause panic in https://github.com/pingcap/tidb/issues/39169

```go
==================
==================
WARNING: DATA RACE
Write at 0x00c0007eceb0 by goroutine 589:
  runtime.recvDirect()
      /usr/local/go/src/runtime/chan.go:348 +0x7c
  github.com/tikv/client-go/v2/internal/client.(*batchCommandsEntry).error()
      /Users/cs/code/goread/src/github.com/pingcap/client-go/internal/client/client_batch.go:86 +0x130
  github.com/tikv/client-go/v2/internal/client.(*batchCommandsClient).failPendingRequests.func1()
      /Users/cs/code/goread/src/github.com/pingcap/client-go/internal/client/client_batch.go:617 +0xe0
  sync.(*Map).Range()
      /usr/local/go/src/sync/map.go:476 +0x1a8
  github.com/tikv/client-go/v2/internal/client.(*batchCommandsClient).failPendingRequests()
      /Users/cs/code/goread/src/github.com/pingcap/client-go/internal/client/client_batch.go:612 +0xd0
  github.com/tikv/client-go/v2/internal/client.(*batchCommandsClient).recreateStreamingClient()
      /Users/cs/code/goread/src/github.com/pingcap/client-go/internal/client/client_batch.go:794 +0x10c
  github.com/tikv/client-go/v2/internal/client.(*batchCommandsClient).batchRecvLoop()
      /Users/cs/code/goread/src/github.com/pingcap/client-go/internal/client/client_batch.go:702 +0x5c0
  github.com/tikv/client-go/v2/internal/client.(*batchCommandsClient).initBatchClient.func1()
      /Users/cs/code/goread/src/github.com/pingcap/client-go/internal/client/client_batch.go:842 +0xb4

Previous read at 0x00c0007eceb0 by goroutine 601:
  runtime.chansend1()
      /usr/local/go/src/runtime/chan.go:146 +0x2c
  github.com/tikv/client-go/v2/internal/client.(*batchCommandsClient).batchRecvLoop()
      /Users/cs/code/goread/src/github.com/pingcap/client-go/internal/client/client_batch.go:737 +0x8d4
  github.com/tikv/client-go/v2/internal/client.(*batchCommandsClient).initBatchClient.func1()
      /Users/cs/code/goread/src/github.com/pingcap/client-go/internal/client/client_batch.go:842 +0xb4

Goroutine 589 (running) created at:
  github.com/tikv/client-go/v2/internal/client.(*batchCommandsClient).initBatchClient()
      /Users/cs/code/goread/src/github.com/pingcap/client-go/internal/client/client_batch.go:842 +0x318
  github.com/tikv/client-go/v2/internal/client.(*batchCommandsClient).send()
      /Users/cs/code/goread/src/github.com/pingcap/client-go/internal/client/client_batch.go:581 +0x44
  github.com/tikv/client-go/v2/internal/client.(*batchConn).getClientAndSend()
      /Users/cs/code/goread/src/github.com/pingcap/client-go/internal/client/client_batch.go:435 +0x534
  github.com/tikv/client-go/v2/internal/client.(*batchConn).batchSendLoop()
      /Users/cs/code/goread/src/github.com/pingcap/client-go/internal/client/client_batch.go:378 +0xa4
  github.com/tikv/client-go/v2/internal/client.(*connArray).Init.func10()
      /Users/cs/code/goread/src/github.com/pingcap/client-go/internal/client/client.go:337 +0x9c

Goroutine 601 (running) created at:
  github.com/tikv/client-go/v2/internal/client.(*batchCommandsClient).initBatchClient()
      /Users/cs/code/goread/src/github.com/pingcap/client-go/internal/client/client_batch.go:842 +0x318
  github.com/tikv/client-go/v2/internal/client.(*batchCommandsClient).send()
      /Users/cs/code/goread/src/github.com/pingcap/client-go/internal/client/client_batch.go:581 +0x44
  github.com/tikv/client-go/v2/internal/client.(*batchConn).getClientAndSend()
      /Users/cs/code/goread/src/github.com/pingcap/client-go/internal/client/client_batch.go:439 +0x7f0
  github.com/tikv/client-go/v2/internal/client.(*batchConn).batchSendLoop()
      /Users/cs/code/goread/src/github.com/pingcap/client-go/internal/client/client_batch.go:378 +0xa4
  github.com/tikv/client-go/v2/internal/client.(*connArray).Init.func10()
      /Users/cs/code/goread/src/github.com/pingcap/client-go/internal/client/client.go:337 +0x9c
==================
```

### PR DESCRIPTION
**Pull request by crazycs520**
close #1222  , https://github.com/pingcap/tidb/issues/51728

### CODE REVIEW

File: internal/client/client_batch.go [hunk 1]
```diff
@@ -579,7 +586,6 @@ func (c *batchCommandsClient) send(forwardedHost string, req *tikvpb.BatchComman
 			zap.String("forwardedHost", forwardedHost),
 			zap.Error(err),
 		)
-		c.failPendingRequests(err)
```
Comment (crazycs520) [inline internal/client/client_batch.go:582]: This is introduced by https://github.com/pingcap/tidb/pull/12819 , need to do more test about this to avoid regression.

**Review by bufferflies — APPROVED** [review]

File: internal/client/client_batch.go (hunk 1 above)
Comment (crazycs520) [reply internal/client/client_batch.go:591]: I got it, and already add test for it.

File: internal/client/client_batch.go [hunk 2]
```diff
@@ -604,23 +604,50 @@ func (c *batchCommandsClient) send(forwardedHost string, req *tikvpb.BatchComman
...
-		entry.error(err)
+		if entry.forwardedHost == forwardedHost {
+			c.failRequest(err, id, entry)
+		}
 		return true
 	})
 }
 
+// fastFailRequests fast fails requests by requestID.
+func (c *batchCommandsClient) fastFailRequests(err error, requestIDs []uint64) {
```
Comment (zyguan) [inline internal/client/client_batch.go:635]: How about to rename it to `failRequestsByIDs`?

**Review by zyguan — APPROVED** [review]
LGTM

File: internal/client/client_batch.go (hunk 2 above)
Comment (crazycs520) [reply internal/client/client_batch.go]: great, done.

**Review by cfzjywxk — COMMENTED** [review]
Any other possible risks of incompatiblity bettween the newly introduced limiter and batch client?

**Review by you06 — APPROVED** [review]

**Comment by crazycs520** [comment]
> Any other possible risks of incompatiblity bettween the newly introduced limiter and batch client?

I haven't found any other problems yet.

**Review by cfzjywxk — APPROVED** [review]
