### PR TITLE
fix issue read req timeout bug cause by pr#1223

### LINKED ISSUE #1231: TiKVClientReadTimeout feature not work after pr #1223
#1223 will cause following test failed in TiDB, since #1223 will affect `TiKVClientReadTimeout` feature.

[jenkins / pingcap/tidb/ghpr_check2 / ghpr_check2 / #6011](https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_check2/detail/ghpr_check2/6011/pipeline/)

    session_fail_test.go:275: 
                Error Trace:        tests/realtikvtest/sessiontest/session_fail_test.go:275
                Error:              Expect "[Point_Get_1 1.00 0 root table:t time:13.2s, loops:1, RU:0.000000, Get:{num_rpc:13, total_time:160.4ms},tikvRPC_backoff:{num:12, total_time:13s},regionMiss_backoff:{num:1, total_time:2ms}, total_process_time: 64.7µs, total_wait_time: 57.1µs, tikv_wall_time: 143.9µs, scan_detail: {total_keys: 1, get_snapshot_time: 15.1µs, rocksdb: {block: {}}} handle:1 N/A N/A]" to match ".*Point_Get.* Get:{num_rpc:4, total_time:.*"
                Test:               TestTiKVClientReadTimeout

### PR DESCRIPTION
**Pull request by crazycs520**
close #1231

### CODE REVIEW

**Review by you06 — APPROVED** [review]

**Review by cfzjywxk — APPROVED** [review]

File: internal/locate/region_request.go [hunk 1]
```diff
@@ -2029,6 +2029,9 @@ func (s *RegionRequestSender) onSendFail(bo *retry.Backoffer, ctx *RPCContext, r
 }
 
 func isCauseByDeadlineExceeded(err error) bool {
+	if errConn, ok := err.(*client.ErrConn); ok {
+		err = errConn.Unwrap()
+	}
```
Comment (zyguan) [inline internal/locate/region_request.go:2034]: Why not to implement the causer interface for `ErrConn`?

Comment (crazycs520) [reply internal/locate/region_request.go:2034]: Nice catch, implement the [causer](https://pkg.go.dev/github.com/pkg/errors#readme-retrieving-the-cause-of-an-error) is a better way to fix. Done.

**Review by zyguan — APPROVED** [review]

**Comment by you06** [comment]
Race detected in the added test.
