### PR TITLE
Fix the issue that leader change with nea leader info cause invalidStore state and lead to unnecessary backoff

### LINKED ISSUE #1112: NotLeader error may cause unnecessary backoff by causing pseudo region error
When a `NotLeader` error carrying a new leader info is received from TiKV, we update the leader info of the region by updating the struct `Region` 's `store` field which is in type `RegionStore`). As the `Region` is a type of shared data managed by `RegionCache`, the `store` is updated by replacing atomic pointers, and thus `RegionStore` is used in copy-on-write pattern.

https://github.com/tikv/client-go/blob/abda04c22acf06d9922fbd20c5dc82b1764b62d0/internal/locate/region_cache.go#L2451-L2454

Then, #264 introduces this which is executed every time attempting to send a request:

https://github.com/tikv/client-go/blob/abda04c22acf06d9922fbd20c5dc82b1764b62d0/internal/locate/region_request.go#L1023-L1026

This forces the replicaSelector to be rebuilt when retrying on `NotLeader` error, by return nil rpcCtx:

https://github.com/tikv/client-go/blob/abda04c22acf06d9922fbd20c5dc82b1764b62d0/internal/locate/region_request.go#L894-L897

and then triggering pseudo region error:

https://github.com/tikv/client-go/blob/abda04c22acf06d9922fbd20c5dc82b1764b62d0/internal/locate/region_request.go#L1424-L1435

This will cause backoff to the caller of `SendReqCtx`, which is unnecessary in a `NotLeader` case where the new leader is immediately known.

### PR DESCRIPTION
**Pull request by MyonKeminta**
Fixes #1112

### CODE REVIEW

**Comment by MyonKeminta** [comment]
@crazycs520 @zyguan @cfzjywxk PTAL
@crazycs520 I directly used your test code, if you don't mind 😥

File: internal/locate/region_request.go [hunk 1]
```diff
@@ -1008,6 +1009,10 @@ func (s *replicaSelector) proxyReplica() *replica {
 	return nil
 }
 
+func sliceIdentical[T any](a, b []T) bool {
```
Comment (cfzjywxk) [inline internal/locate/region_request.go:1012]: Better to comment about this function.

**Review by cfzjywxk — APPROVED** [review]

**Review by zyguan — APPROVED** [review]

**Review by crazycs520 — APPROVED** [review]

**Comment by crazycs520** [comment]
@MyonKeminta Could you cherry-pick this PR to [tidb-6.5-with-kv-timeout-feature](https://github.com/tikv/client-go/tree/tidb-6.5-with-kv-timeout-feature) branch?
