### PR TITLE
fix issue replica selector v2 not compatible with v1 in mixed mode

### LINKED ISSUE #1268: replica selector v2 not compatible with v1 in mixed mode
# Issue

### 1. Minimal reproduce step

This issue was found in #1267

```go
	s.changeRegionLeader(3)
	ca = replicaSelectorAccessPathCase{
		reqType:   tikvrpc.CmdGet,
		readType:  kv.ReplicaReadMixed,
		staleRead: false,
		accessErr: []RegionErrorType{ServerIsBusyErr, ServerIsBusyErr, ServerIsBusyErr},
```

### 2. What did you expect to see?

```go
		expect: &accessPathResult{
			accessPath: []string{
				"{addr: store1, replica-read: true, stale-read: false}",
				"{addr: store2, replica-read: true, stale-read: false}",
				"{addr: store3, replica-read: true, stale-read: false}",
			},
```

### 3. What did you see instead?

```go
		expect: &accessPathResult{
			accessPath: []string{
				"{addr: store1, replica-read: true, stale-read: false}",
				"{addr: store3, replica-read: true, stale-read: false}",
				"{addr: store2, replica-read: true, stale-read: false}",
			},
```

### PR DESCRIPTION
**Pull request by crazycs520**
close #1268

### CODE REVIEW

File: internal/locate/replica_selector_test.go [hunk 1]
```diff
@@ -663,6 +663,28 @@ func TestReplicaReadAccessPathByCase(t *testing.T) {
 		},
 	}
 	s.True(s.runCaseAndCompare(ca))
+
+	s.changeRegionLeader(3)
+	ca = replicaSelectorAccessPathCase{
```
Comment (cfzjywxk) [inline internal/locate/replica_selector_test.go:668]: We could also cover the `req.ReplicaReadType == kv.ReplicaReadPreferLeader` case.

Comment (crazycs520) [reply internal/locate/replica_selector_test.go:668]: done.

**Review by cfzjywxk — APPROVED** [review]

**Review by zyguan — APPROVED** [review]
