### PR TITLE
Fix stale read metrics

### LINKED ISSUE #1648: missing stale read metrics when the stale read is failed
From the KV errors, a lot of stale read requests are failed, but the correspond ops/traffic metrics are not tracked.

Image

Image

### PR DESCRIPTION
**Pull request by you06**
close #1648

Record the stale-read metrics correctly.

- Hit
image

- Miss
image
image

### CODE REVIEW

File: internal/locate/region_request.go [hunk 1]
```diff
@@ -571,6 +574,16 @@ func (s *RegionRequestSender) SendReqAsync(
...
+		if stmtExec := ctx.Value(util.ExecDetailsKey); stmtExec != nil {
+			execDetails := stmtExec.(*util.ExecDetails)
+			atomic.AddInt64(&execDetails.WaitKVRespDuration, int64(time.Since(startTime)))
+			collector := networkCollector{}
+			if state.invariants.staleRead {
+				collector.staleReadMetricsCollector = &staleReadMetricsCollector{}
+			}
+			collector.onReq(req, execDetails)
+			collector.onResp(req, resp, execDetails)
+		}
```
Comment (zyguan) [inline internal/locate/region_request.go]: Should we move it to [here](https://github.com/tikv/client-go/blob/af9bd3c5d2d5d2b5b7b0cc4e175d6b96877de9f7/internal/locate/region_request.go#L1268)?

Comment (you06) [reply internal/locate/region_request.go]: Yes we can.
What do you think about the stmt exec details in the context, may we track the traffic even we're not collecting the exec details?

Comment (zyguan) [reply internal/locate/region_request.go]: > What do you think about the stmt exec details in the context, may we track the traffic even we're not collecting the exec details?

I think it would be better to do so, maybe extract `staleReadMetricsCollector` from `networkCollector` or allow `networkCollector` methods accept a nil `ExecDetails`?

**Comment by you06** [comment]
@cfzjywxk @zyguan PTAL again.

File: internal/locate/region_request.go [hunk 2]
```diff
@@ -1114,6 +1129,17 @@ func (s *sendReqState) send() (canceled bool) {
...
+
+		if stmtExec := ctx.Value(util.ExecDetailsKey); stmtExec != nil {
+			execDetails := stmtExec.(*util.ExecDetails)
+			atomic.AddInt64(&execDetails.WaitKVRespDuration, int64(rpcDuration))
+			collector := networkCollector{
+				staleRead: s.invariants.staleRead,
+			}
+			collector.onReq(req, execDetails)
+			collector.onResp(req, s.vars.resp, execDetails)
+		}
```
Comment (zyguan) [inline internal/locate/region_request.go:1137]:
```go
var execDetails *util.ExecDetails
if val := ctx.Value(util.ExecDetailsKey); val != nil {
	execDetails = val.(*util.ExecDetails)
	atomic.AddInt64(&execDetails.WaitKVRespDuration, int64(rpcDuration))
}
collector := networkCollector{staleRead: s.invariants.staleRead}
collector.onReq(req, execDetails)
collector.onResp(req, resp, execDetails)
```

**Review by zyguan — APPROVED** [review]

**Review by cfzjywxk — APPROVED** [review]
